---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  flog:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-51
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- bin/
- config/
- db/
- docs/
- spec/
- test/
